# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-05 07:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_auto_20180218_1744'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=4, max_digits=11)),
                ('type', models.CharField(choices=[('1', 'repay'), ('2', 'consumption'), ('3', 'other'), ('4', 'repay')], max_length=1)),
                ('remarks', models.TextField()),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('expenditure', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.User')),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=4, max_digits=11)),
                ('type', models.CharField(choices=[('1', 'salary'), ('2', 'loan'), ('2', 'other')], max_length=1)),
                ('remarks', models.TextField()),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('repay_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=11, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.User')),
            ],
        ),
    ]
